config/routes.rb
Rails.application.routes.draw do
  
  get 'pages/home'

  get 'pages/about' => 'pages#about', as: 'about'

  get 'pages/courses' => 'pages#courses', as: 'courses'

  get 'pages/locations' => 'pages#locations', as: 'locations'
 
  get 'pages/contacts' => 'pages#contacts', as: 'contacts'

  root 'pages#home'
 

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about

  end

  def courses
    
  end

  def locations
  
  end

  def contacts

  end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_header.html.erb
<div id="topNav">
  <%= link_to 'Courses', courses_path(), {:class=>"nav"} %>
  <%= link_to 'Location', locations_path(), {:class=>"nav"} %>
  <%= link_to 'Home', root_path(), {:class=>"nav"} %> 
  <%= link_to 'Contacts', contacts_path(), {:class=>"nav"} %>
  <%= link_to 'About Us', about_path(), {:class=>"nav"} %> 
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield :title %></title>
  
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>


</body>
</html
  

app/views/pages/about.html.erb
<%=content_for :title1, 'About us | Griffith' %>

<h1> About Us </h1>

  <%= render 'layouts/header'%>

<p> Griffith College prides itself on the graduates we have produced over the past 40 years.These ambitious, enterprising and talented young men and women have carved out notable careers across a diverse range of industries.</p>

app/views/pages/contacts.html.erb
<%=content_for :title, 'Contact Us | Griffith' %>

<h1>Contact Us</h1>

  <%= render 'layouts/header'%>

<p>Established in 1974, Griffith College provides a wide range of full and part-time certificate, diploma, degree and postgraduate courses and is home to over 7,000 students. Our campuses are easily accessible via car and public transport and centrally located within each city, so you have a wide range of amenities on your doorstep. Each campus has its own unique history and character. For more information on our locations in Cork, Dublin and Limerick please choose from the options below.</p>

app/views/pages/courses.html.erb
<%=content_for :title, 'Courses | Griffith' %>

<h1>Courses</h1>

  <%= render 'layouts/header'%>


<p>Hello there</p>

app/views/pages/home.html.erb
<%=content_for :title, 'Griffith' %>

<h1> Welcome to Griffith </h1>

<p>Study at Griffith College – Dublin, Cork and Limerick</p>

<%= image_tag "GCD.jpg", :height => 127, :width => 212 =%>

<%= link_to 'Courses', courses_path() %> <%= link_to 'Location', locations_path() %> <%= link_to 'Home', root_path() %> <%= link_to 'Contacts', contacts_path() %> <%= link_to 'About Us', about_path() %> 

app/views/pages/locations.html.erb
<%=content_for :title, 'Locations | Griffith' %>

<h1> Locations </h1>

  <%= render 'layouts/header'%>

<p>Established in 1974, Griffith College provides a wide range of full and part-time certificate, diploma, degree and postgraduate courses and is home to over 7,000 students. Our campuses are easily accessible via car and public transport and centrally located within each city, so you have a wide range of amenities on your doorstep. Each campus has its own unique history and character. For more information on our locations in Cork, Dublin and Limerick please choose from the options below.</p>